apiVersion: apps/v1
kind: Deployment
metadata:
  name: bpdmspaymentinstrument
spec:
  replicas: 10
  selector:
    matchLabels:
      app: bpdmspaymentinstrument
  template:
    metadata:
      labels:
        app: bpdmspaymentinstrument
      annotations:
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
        prometheus.io/scrape: 'true'
    spec:
      containers:
        - name: bpdmspaymentinstrument
          image: cstaruatregistry.azurecr.io/bpdmspaymentinstrument
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: postgres-credentials
            - secretRef:
                name: bpdmspaymentinstrument
            - configMapRef:
                name: eventhub-logging
            - configMapRef:
                name: eventhub-common
            - configMapRef:
                name: bpdmspaymentinstrument
            - configMapRef:
                name: jvm
      hostAliases:
        - hostnames:
            - bpd-event-uat.servicebus.windows.net
          ip: 10.70.67.5
